import datetime
import os

def concat_shaders():
    output = 'particle_chunks.js'
    dirs = ['./']

    with open(output, 'w') as out:
        out.write("// autogenerated at: %s\n" % datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))
        for dir in dirs:
            for filename in os.listdir(dir):
                if filename.endswith(".vs") or filename.endswith(".ps"):
                    path = dir + filename
                    with open(path, 'r') as f:
                        name = os.path.splitext(filename)[0] + os.path.splitext(filename)[1][1:].upper()
                        content = f.read().replace("\n", "\\n")
                        out.write('pc.shaderChunks.%s = "%s"\n' % (name, content))

concat_shaders()
